name: Deploy to VPS

on:
  push:
    branches:
      - main
      - uat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          BRANCH: ${{ github.ref_name }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          if [ "${BRANCH}" = "main" ]; then
            PROJECT_DIR="services-financiers-etudiants-api"
          elif [ "${BRANCH}" = "uat" ]; then
            PROJECT_DIR="services-financiers-etudiants-api-uat"
          else
            echo "❌ Branche ${BRANCH} non prévue pour le déploiement"
            exit 1
          fi

          echo "🚀 Déploiement sur dossier: $PROJECT_DIR"

          ssh $VPS_USER@$VPS_HOST << EOF
            cd $PROJECT_DIR
            git pull origin $BRANCH

            if [ "${BRANCH}" = "main" ]; then
              docker-compose -f docker-compose.yml up -d --build
            elif [ "${BRANCH}" = "uat" ]; then
              docker-compose -f docker-compose.uat.yml up -d --build
            fi
          EOF
